### ISSUE TITLE
크롬을쓸때 버그가 생겼네요

### ISSUE THREAD

**Issue by ghost** [dasom-im/dasom-gtk#2]
_From @jgyuseok on December 8, 2015 3:51_

크롬버전은 45.0.2454.101 Ubuntu 14.04 (64-bit) 사용중이고 우분투 14.04 LTS 에 KDE데스크탑 환경 깔아 서 쓰고있습니다 

다른 프로그램은 문제가 없는데 크롬만 이렇 게띄어쓰기 가이상하게 되네 요

다솜 입력기만 그런것이 아니라 ibus도 같은 현상이 있네요 잘쓰다 어느순간 갑자기 이렇게된거라 정확히 언제 오류가 났는지는 파악이 안됩니다 

_Copied from original issue: cogniti/dasom#29_

**Comment by ghost** [comment]
제 생각엔 dasom-gtk 가 설치되지 않은 것 같습니다. 사용 중인 dasom 버전과 배포판 종류와 배포판 버전을 알려주세요.
2015. 12. 8. 오후 12:51에 "jgyuseok" notifications@github.com님이 작성:

**Comment by ghost** [comment]
_From @jgyuseok on December 8, 2015 5:20_

kubuntu 14.04에 다솜은 1.0버전 사용중입니다

**Comment by ghost** [comment]
다음의 명령으로 공식 다솜 PPA 저장소 추가합니다.

```
sudo add-apt-repository ppa:dasom/ppa
```

공식 다솜 PPA 저장소 추가 후에

```
sudo apt-get update
sudo apt-get install dasom dasom-gtk dasom-qt dasom-jeongeum
```

로그아웃, 로그인하시고
크롬을 실행해 보시고 결과 알려주세요.
2015. 12. 8. 오후 2:20에 "jgyuseok" notifications@github.com님이 작성:

**Comment by ghost** [comment]
_From @jgyuseok on December 8, 2015 5:41_

여전히 같은증상이 일어납니다

**Comment by ghost** [comment]
터미널에서
export | grep ibus
실행하여 결과를 올려주세요.

export | grep dasom
실행하여 결과를 올려주세요.
2015. 12. 8. 오후 2:41에 "jgyuseok" notifications@github.com님이 작성:

**Comment by ghost** [comment]
_From @jgyuseok on December 8, 2015 6:26_

```
export | grep dasom은 XMODIFIERS='@im=dasom'
export | grep ibus 은 아에 안나옵니다 
```

**Comment by ghost** [comment]
@jgyuseok

ubuntu-14.04.3-desktop-amd64.iso 를 버추얼박스에서 설치하면서
한국어를 선택하였고, 영어 드보락을 선택하여 설치를 완료하여 재부팅 후,
`시스템 설정`에서 `언어 지원`으로 들어가서 키보드 입력기에서 `IBus`를 `없음`으로 변경하였습니다.

시스템 설정 --> 키보드 --> 런처 --> 허드를 표시할 키 --> 사용 안 함

으로 설정하였습니다.

gnome-terminal 을 열어서

```
sudo add-apt-repository ppa:dasom/ppa
sudo apt-get update
sudo apt-get install dasom dasom-gtk dasom-qt dasom-jeongeum
```

을 실행합니다.

```
im-config
```

을 실행하여 dasom 을 선택합니다.

`로그아웃 / 로그인` 합니다.

다시 gnome-terminal 을 엽니다.

```
export | grep dasom
declare -x GTK_IM_MODULE="dasom"
declare -x QT4_IM_MODULE="dasom"
declare -x QT_IM_MODULE="dasom"
declare -x XMODIFIERS="@im=dasom"
```

가 정상적으로 표시되는 것을 확인하였습니다.

버추얼박스에서 작업하고 있으므로,
다음은 `Alt키`를 `한글키`로 사용하여 한영 전환을 확인하기 위함입니다.

dconf-editor 을 실행합니다.
org -- freedesktop -- dasom -- engines -- jeongeum 으로 이동합니다.
`korean-101-104-key-compatible [v]` 체크합니다.

다시 gnome-terminal 로 돌아와서 `Alt키` 로 한/영 전환이 정상적으로 작동하는 것을 확인하였습니다.

**Comment by ghost** [comment]
지금 크롬을 다운받고 있는데, 정상적으로 작동할 것으로 예상합니다.
@jgyuseok 님 컴퓨터에 어딘가에서 설정이 잘못되어 있을 것입니다.
다음의 명령을 실행하여 dasom이 정상적으로 설치되었는지 확인합니다.

```
dpkg --list | grep dasom
find /usr | grep dasom
```

결과를 올려주세요.

아울러 cat .xinputrc 결과도 올려주시기 바랍니다.
터미널 열어서 아래처럼 하면 됩니다.

```
cd
cat .xinputrc
```

이 결과를 올려주시기 바랍니다.

**Comment by Silica96** [comment]
```
dpkg --list | grep dasom

ii  dasom                                                       1.2-1~trusty                                        amd64        Input Method Framework
ii  dasom-gtk                                                   1.2-1~trusty                                        amd64        GTK+ IM modules for Dasom
ii  dasom-jeongeum                                              1.1-1~trusty                                        amd64        Korean language engine module for Dasom
ii  dasom-qt                                                    1.2-1~trusty                                        amd64        Qt IM modules for Dasom


===================================================================
find /usr | grep dasom

/usr/share/gnome-shell/extensions/dasom-agent@gnome-shell-extensions.cogno.org
/usr/share/gnome-shell/extensions/dasom-agent@gnome-shell-extensions.cogno.org/extension.js
/usr/share/gnome-shell/extensions/dasom-agent@gnome-shell-extensions.cogno.org/metadata.json
/usr/share/gnome-shell/extensions/dasom-agent@gnome-shell-extensions.cogno.org/stylesheet.css
/usr/share/icons/hicolor/24x24/status/dasom-indicator-ko.png
/usr/share/icons/hicolor/24x24/status/dasom-indicator.png
/usr/share/icons/hicolor/24x24/status/dasom-indicator-warning.png
/usr/share/icons/hicolor/24x24/status/dasom-indicator-en.png
/usr/share/icons/hicolor/scalable/status/dasom-indicator-warning.svg
/usr/share/icons/hicolor/scalable/status/dasom-indicator-ko.svg
/usr/share/icons/hicolor/scalable/status/dasom-indicator.svg
/usr/share/icons/hicolor/scalable/status/dasom-indicator-en.svg
/usr/share/icons/hicolor/32x32/status/dasom-indicator-ko.png
/usr/share/icons/hicolor/32x32/status/dasom-indicator.png
/usr/share/icons/hicolor/32x32/status/dasom-indicator-warning.png
/usr/share/icons/hicolor/32x32/status/dasom-indicator-en.png
/usr/share/icons/hicolor/22x22/status/dasom-indicator-ko.png
/usr/share/icons/hicolor/22x22/status/dasom-indicator.png
/usr/share/icons/hicolor/22x22/status/dasom-indicator-warning.png
/usr/share/icons/hicolor/22x22/status/dasom-indicator-en.png
/usr/share/locale/ko/LC_MESSAGES/dasom-gtk.mo
/usr/share/locale/ko/LC_MESSAGES/dasom.mo
/usr/share/im-config/data/70_dasom.rc
/usr/share/im-config/data/70_dasom.conf
/usr/share/lintian/overrides/dasom
/usr/share/lintian/overrides/dasom-jeongeum
/usr/share/doc/dasom-gtk
/usr/share/doc/dasom-gtk/copyright
/usr/share/doc/dasom-gtk/changelog.Debian.gz
/usr/share/doc/dasom-qt
/usr/share/doc/dasom-qt/copyright
/usr/share/doc/dasom-qt/changelog.Debian.gz
/usr/share/doc/dasom
/usr/share/doc/dasom/copyright
/usr/share/doc/dasom/changelog.Debian.gz
/usr/share/doc/dasom-jeongeum
/usr/share/doc/dasom-jeongeum/copyright
/usr/share/doc/dasom-jeongeum/changelog.Debian.gz
/usr/bin/dasom-indicator
/usr/bin/dasom-daemon
/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-dasom-gtk2.so
/usr/lib/x86_64-linux-gnu/dasom
/usr/lib/x86_64-linux-gnu/dasom/modules
/usr/lib/x86_64-linux-gnu/dasom/modules/dasom-jeongeum.so
/usr/lib/x86_64-linux-gnu/libdasom.so
/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-dasom-gtk3.so
/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libqt5im-dasom.so
/usr/lib/x86_64-linux-gnu/qt4/plugins/inputmethods/libqt4im-dasom.so


==================================================================
cat .xinputrc

#im-config(8) generated on Tue, 08 Dec 2015 14:09:30 +0900
run_im dasom
#im-config signiture: 7c86e96a7b9dae3650d6f9f369d883da  -
```

**Comment by ghost** [comment]
크롬 실행하여 확인했는데 정상적으로 작동합니다.
크롬 버전은 47.0.2526.73 (64-bit) 입니다.

jgyuseok 님이 겪는 문제는 다솜 입력기 버그가 아닙니다.
입력기 설정이 어딘가에 잘못되어 있어서 나타나는 현상입니다.
터미널에서 

```
export | grep dasom
declare -x GTK_IM_MODULE="dasom"
declare -x QT4_IM_MODULE="dasom"
declare -x QT_IM_MODULE="dasom"
declare -x XMODIFIERS="@im=dasom"
```

위에 처럼 나와야 하는데..

```
declare -x XMODIFIERS="@im=dasom"
```

이렇게 하나만 설정이 되어 있습니다.

그래서 크롬 실행하면 XIM 으로 입력을 받기 때문에 그러한 현상이 나타나는 것입니다.
관련 이슈 https://github.com/dasom-im/dasom/issues/8

어디가 잘못 되었는지 제가 찾아드릴 수 없습니다.
jgyuseok 님께서 어떤 작업을 하셨는지 잘 떠올려보시기 바랍니다.

해결을 못하시면 일단, 터미널 열고 아래처럼 실행하여 사용하시기 바랍니다.

```
export GTK_IM_MODULE="dasom"
/opt/google/chrome/chrome
```

이 이슈는 다솜 입력기 문제가 아니므로 닫겠습니다.

감사합니다.

**Comment by ghost** [comment]
kubuntu-14.04.3-desktop-amd64.iso 을 다운로드 받는데 시간이 오려 걸려서 이제서야
kubuntu-14.04.3-desktop-amd64.iso 를 버추얼박스에 설치하여 테스트해봤습니다.
im-config 가 정상 작동하지 않아서 `-c` 옵션을 주어

```
im-config -c
```

로 dasom 을 선택할 수 있었습니다.

로그아웃 / 로그인 후에 konsole 에서

```
export | grep dasom
declare -x GTK_IM_MODULE="dasom"
declare -x QT4_IM_MODULE="dasom"
declare -x QT_IM_MODULE="dasom"
declare -x XMODIFIERS="@im=dasom"
```

환경 변수가 정상임을 확인하였습니다.
dconf-editor 에서
org -- freedesktop -- dasom -- engines -- jeongeum 에 가보니 아무 것도 표시되질 않았습니다.
리부팅을 해도 마찬가지였습니다.

```
sudo apt-get update
sudo apt-get upgrade
```

후에, 리부팅 후에 다시 dconf-editor 실행해보니
org -- freedesktop -- dasom -- engines -- jeongeum 에 항목이 나타났습니다.
`korean-101-104-key-compatible [v]` 체크하였습니다.
그 후 크롬, 파이어폭스에서 다솜 입력기로 입력하는데 정상 작동하였습니다.
그런데 뭔가 특이점이 있었는데, firefox는 focus in / out 할 때 다솜 표시기가 정상 작동하는데,
konsole 의 경우 focus in / out 할 때 다솜 표시기가 바뀌어야 하는데 바뀌지 않고 그대로였습니다.
이 부분은 나중에 확인하겠습니다.

**Comment by ghost** [comment]
엉뚱하게도 dasom-qt 에 초점 버그를 발견하여 초점 버그를 일부 고쳤습니다.
감사합니다.
https://github.com/dasom-im/dasom-qt/commit/200e457afcaaea4b9e81098eb3d32f3e5d4f1907
https://github.com/dasom-im/dasom-qt/commit/d5df097da9f4d03f86de2be26ce119e05e483b87
https://github.com/dasom-im/dasom-qt/commit/e3fc0bd2c016ce512afd77798967e273e620a150
https://github.com/dasom-im/dasom-qt/commit/f9f9e854c1515be93a8e1e7157d82fa9c030feb7  dasom-qt 1.2.2 released 했습니다.

초점 버그가 완전히 고쳐진 것은 아닙니다. Qt 관련하여 불편이 있으시면 제가 재현할 수 있도록 https://github.com/dasom-im/dasom-qt/issues 에 이슈를 올려주세요. 감사합니다.
